### ISSUE TITLE
Conclusions/Grades

### ISSUE THREAD

**Issue by bwestergard** [plaid/async-problem#17]
So, what's the verdict?

**Comment by davidchambers** [comment]
> Solutions are graded on the following criteria:
>
>   - the size of `main` (smaller is better); and
>   - the degree to which the approach facilitates breaking the problem into manageable subproblems.

| Solution                    | Small `main`        | Decomposed          |
| --------------------------- |:-------------------:|:-------------------:|
| [callbacks.js][1]           | :x:                 | :x:                 |
| [async.js][2]               | :x:                 | :x:                 |
| [kgo.js][3]                 | :x:                 | :x:                 |
| [promises.js][4]            | :x:                 | :white_check_mark:  |
| [promises-ramda.js][5]      | :white_check_mark:  | :white_check_mark:  |
| [coroutines-co.js][6]       | :x:                 | :x:                 |
| [coroutines-bluebird.js][7] | :white_check_mark:  | :x:                 |
| [await.js][8]               | :x:                 | :x:                 |
| [tasks.js][9]               | :white_check_mark:  | :white_check_mark:  |


[1]: https://github.com/plaid/async-problem/blob/master/callbacks.js
[2]: https://github.com/plaid/async-problem/blob/master/async.js
[3]: https://github.com/plaid/async-problem/blob/master/kgo.js
[4]: https://github.com/plaid/async-problem/blob/master/promises.js
[5]: https://github.com/plaid/async-problem/blob/master/promises-ramda.js
[6]: https://github.com/plaid/async-problem/blob/master/coroutines-co.js
[7]: https://github.com/plaid/async-problem/blob/master/coroutines-bluebird.js
[8]: https://github.com/plaid/async-problem/blob/master/await.js
[9]: https://github.com/plaid/async-problem/blob/master/tasks.js

**Comment by sahiltalwar88** [comment]
If we're trying to grade these on the basis of how realistically usable they are, it seems to me that we should also consider the overall amount of code as well as conceptual complexity - some of these solutions involve more boilerplate, and some are much more conceptually involved (and thus often lead to more complex, less readable code).

**Comment by davidchambers** [comment]
Readers are free to compare the various options and draw conclusions based on their current requirements and preferences.

> some are much more conceptually involved

If told _Task is a lawful functor_ one programmer may respond with _Great! I know **exactly** how to interact with functors._ Another may respond with _What is a functor? Just show me the API!_

Task is simple; Promise is easy (see [Simple Made Easy][1]). The appropriate choice for a project depends on the relative importance of simplicity and convenience.


[1]: http://www.infoq.com/presentations/Simple-Made-Easy
