### ISSUE TITLE
Proposal to add most to the list

### ISSUE THREAD

**Issue by Risto-Stevcev** [plaid/async-problem#23]
I think it would be good to add [most](https://github.com/cujojs/most) to the list. From the docs it mentions:

Most.js streams are [compatible with Promises/A+ and ES6 Promises](promises).  They also implement [Fantasy Land](https://github.com/fantasyland/fantasy-land) `Monoid`, `Functor`, `Applicative`, and `Monad`.

Which means it should be comparable to the other solutions.

**Comment by davidchambers** [comment]
Good idea. Would you like to submit a pull request?

**Comment by Risto-Stevcev** [comment]
Sure
