### ISSUE TITLE
@most/create

### ISSUE THREAD

**Issue by joaomilho** [plaid/async-problem#32]
The most implementation seems quite unnatural relying so much on promises. Something reading files using `@most/create` would likely be a better example.

I tried to run the examples to change 'em, but got the following error:

```
    throw new TypeError('Path must be a string. Received ' + inspect(path));
```

**Comment by davidchambers** [comment]
Which version of Node are you using, @joaomilho?

**Comment by joaomilho** [comment]
oh so many, but generally 7.x

**Comment by joaomilho** [comment]
Ha, GH swallowed most/create because of the @ character. Fixed now.

**Comment by davidchambers** [comment]
Could you try this?

```console
$ cd /tmp
$ git clone git@github.com:plaid/async-problem.git
$ cd async-problem
$ npm install
$ nvm exec 7 npm test
```

This works for me on macOS 10.13.

**Comment by joaomilho** [comment]
sure

**Comment by joaomilho** [comment]
works

**Comment by davidchambers** [comment]
Great. Feel free to submit a pull request to make the implementation more idiomatic. :)
